//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationDatabaseEntities : DbContext
    {
        public RegistrationDatabaseEntities()
            : base("name=RegistrationDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int RegistrationDelete(string original_Username)
        {
            var original_UsernameParameter = original_Username != null ?
                new ObjectParameter("Original_Username", original_Username) :
                new ObjectParameter("Original_Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrationDelete", original_UsernameParameter);
        }
    
        public virtual ObjectResult<RegistrationInsert_Result> RegistrationInsert(string username, string name, string email, Nullable<System.DateTime> dateOfBirth, string phone)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dateOfBirthParameter = dateOfBirth.HasValue ?
                new ObjectParameter("DateOfBirth", dateOfBirth) :
                new ObjectParameter("DateOfBirth", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegistrationInsert_Result>("RegistrationInsert", usernameParameter, nameParameter, emailParameter, dateOfBirthParameter, phoneParameter);
        }
    
        public virtual ObjectResult<RegistrationSearch_Result> RegistrationSearch(string nameSearchValue, string order, Nullable<int> startRowIndex, Nullable<int> totalRowCount)
        {
            var nameSearchValueParameter = nameSearchValue != null ?
                new ObjectParameter("NameSearchValue", nameSearchValue) :
                new ObjectParameter("NameSearchValue", typeof(string));
    
            var orderParameter = order != null ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(string));
    
            var startRowIndexParameter = startRowIndex.HasValue ?
                new ObjectParameter("StartRowIndex", startRowIndex) :
                new ObjectParameter("StartRowIndex", typeof(int));
    
            var totalRowCountParameter = totalRowCount.HasValue ?
                new ObjectParameter("TotalRowCount", totalRowCount) :
                new ObjectParameter("TotalRowCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegistrationSearch_Result>("RegistrationSearch", nameSearchValueParameter, orderParameter, startRowIndexParameter, totalRowCountParameter);
        }
    
        public virtual ObjectResult<RegistrationUpdate_Result> RegistrationUpdate(string username, string name, string email, string phone, string original_Username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var original_UsernameParameter = original_Username != null ?
                new ObjectParameter("Original_Username", original_Username) :
                new ObjectParameter("Original_Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegistrationUpdate_Result>("RegistrationUpdate", usernameParameter, nameParameter, emailParameter, phoneParameter, original_UsernameParameter);
        }
    }
}
